export const RESTART_AUTH_REPONSE = "RESTART_AUTH_REPONSE";
export const RESTART_ALL_RESPONSE="RESTART_ALL_RESPONSE";
export const RESTART_SINGLE_PRODUCT_RESPONSE="RESTART_SINGLE_PRODUCT_RESPONSE";
export const RESTART_ADD_PRODUCT_RESPONSE="RESTART_ADD_PRODUCT_RESPONSE";
export const LOADING = "LOADING";
export const CODE_ERROR = "CODE_ERROR";

// for signUp
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR ="SIGNUP_ERROR";
// for login
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_ERROR="LOGIN_ERROR";
// for logout
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";
// for Profile Detail
export const LOADPROFILE_SUCCESS="LOAD_PROFILE_SUCCESS";
export const LOADPROFILE_ERROR="LOADPROFILE_ERROR";
// for Adding Product
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL ="ADD_PRODUCT_FAIL"
// for All Products
export const GET_ALL_PRODUCT_SUCCESS="GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_ERROR ="GET_ALL_PRODUCT_ERROR";
// for Single Product Detail
export const GET_SINGLE_PRODUCT_SUCCESS ="GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAIL ="GET_SINGLE_PRODUCT_FAIL";
// for Updating Single Product
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL="UPDATE_PRODUCT_FAIL";
// for Deleting Product
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL";